/**
 * Individual crop sprite URLs (public/crops/*.png).
 *
 * Generated by scripts/split-sprites.mjs from the original 3x3 sprite sheet.
 * Each PNG is tightly cropped to the plant's bounding box with transparent background.
 *
 * Gemini generated 9 distinct vegetables; we map our starter commodity IDs
 * to the best visual stand-in until per-crop sprites are generated.
 */
import type { CommodityId } from '../data/commodities';

export const SPRITE_URLS = {
  carrot: './crops/carrot.png',
  cabbage: './crops/cabbage.png',
  spinach: './crops/spinach.png',
  tomato: './crops/tomato.png',
  pepper: './crops/pepper.png',
  broccoli: './crops/broccoli.png',
  radish: './crops/radish.png',
  kale: './crops/kale.png',
  onion: './crops/onion.png',
} as const;

export type SpriteKey = keyof typeof SPRITE_URLS;

export const CROP_SPRITE: Partial<Record<CommodityId, SpriteKey>> = {
  corn: 'tomato',      // red fruit stands out
  wheat_srw: 'spinach', // leafy green
  soybean: 'broccoli',  // bushy green
};

export function spriteUrlForCrop(cropId: CommodityId): string | null {
  const key = CROP_SPRITE[cropId];
  return key ? SPRITE_URLS[key] : null;
}
